
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineShopping.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_City
{

    public int CityId { get; set; }

    public int StateId { get; set; }

    public string CityName { get; set; }

    public bool IsActive { get; set; }

    public bool IsDelete { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual Tbl_State Tbl_State { get; set; }

}

}
