
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineShopping.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_State
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tbl_State()
    {

        this.Tbl_City = new HashSet<Tbl_City>();

    }


    public int StateId { get; set; }

    public int CountryId { get; set; }

    public string StateName { get; set; }

    public string StateCode { get; set; }

    public bool IsActive { get; set; }

    public bool IsDelete { get; set; }

    public System.DateTime CreatedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_City> Tbl_City { get; set; }

    public virtual Tbl_Country Tbl_Country { get; set; }

}

}
