
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Grocery.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Country
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tbl_Country()
    {

        this.Tbl_State = new HashSet<Tbl_State>();

    }


    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public string CountryCode { get; set; }

    public bool IsActive { get; set; }

    public bool IsDelete { get; set; }

    public System.DateTime CreatedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_State> Tbl_State { get; set; }

}

}
