
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Grocery.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Vendors
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tbl_Vendors()
    {

        this.Tbl_Product = new HashSet<Tbl_Product>();

    }


    public int VendorId { get; set; }

    public int MemberId { get; set; }

    public string CompanyName { get; set; }

    public string GSTNumber { get; set; }

    public string BusinessLicense { get; set; }

    public string Address { get; set; }

    public Nullable<int> Pincode { get; set; }

    public bool IsActive { get; set; }

    public bool IsDelete { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual Tbl_Members Tbl_Members { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }

}

}
